solon.app:
  name: demoapp
  group: demo

solon.logging.appender:
  console:
    level: TRACE
  file:
    name: "logs/demo2"
    rolling: "logs/${solon.app.name}_%d{yyyy-MM-dd_HH_mm}/%i.log"
    level: INFO
    maxFileSize: "10 MB"
    maxHistory: "7"
