server.port: 8082

solon.app:
  name: docapi
  group: demo


knife4j.enable: true
knife4j.production: false
knife4j.basic.enable: true
knife4j.basic.username: admin
knife4j.basic.password: 123456
knife4j.setting.enableOpenApi: false
knife4j.setting.enableSwaggerModels: true
knife4j.setting.enableFooter: false
knife4j.setting.enableFooterCustom: true
knife4j.setting.footerCustomContent: Apache License 2.0 | Copyright 2022-[SNOWY](https://www.xiaonuo.vip)

solon.cloud.nacos:
  server: "localhost:8848"           #nacos2 服务地址

solon.docs:
  discover:
    pathPattern: "swagger/v2?group=adminApi"
    syncStatus: true
    excluded:
      - "user-api"
    included:
      - "demoapi"
#  routes:
#    adminApi:
#      groupName: "admin端接口"
#      upstream:
#        service: "demoapi"
#        path: "swagger/v2?group=adminApi"
