solon.app:
    name: demoapp
    group: demo

#solon.dataSources:
#    db1!:
#        class: "com.zaxxer.hikari.HikariDataSource"
#        schema: rock
#        jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
#        driverClassName: com.mysql.jdbc.Driver
#        username: root
#        password: 123456
#        url: ${.jdbcUrl}

solon.dataSources:
    db1!:
        class: "com.zaxxer.hikari.HikariDataSource"
        jdbcUrl: "jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;IGNORECASE=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE"
        driverClassName: "org.h2.Driver"

#默认
mybatis.db1:
    typeAliases:    #支持包名 或 类名 //支持 ** 和 *
        - "demo4031.model"
#        - "demo4031.*.AppxModel"
    mappers:        #支持包名 或 类名 或 xml（.xml结尾）//支持 ** 和 *
        - "demo4031.dso.mapper"
#        - "classpath:demo4031/dso/mapper/*.xml"
    configuration:
        cacheEnabled: false
        mapperVerifyEnabled: false
        mapUnderscoreToCamelCase: true
        logImpl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    globalConfig:
        banner: false
        metaObjectHandler: "demo4031.dso.MetaObjectHandlerImpl"
        dbConfig:
            logicDeleteField: "deleted"
            logicDeleteValue: "2"
